projects:
  - name: mongoose
    language: JavaScript
    type: ODM
    repo: "Automattic/mongoose"
    npm: "mongoose"
    stackoverflow: "mongoose"

  - name: Prisma MongoDB
    language: JavaScript
    type: ORM
    repo: "prisma/prisma"
    npm: "prisma"
    stackoverflow: "prisma"

  - name: Spring Data MongoDB
    language: Java
    type: Framework
    repo: "spring-projects/spring-data-mongodb"
    maven:
      group: "org.springframework.data"
      artifact: "spring-data-mongodb"
    stackoverflow: "spring-data-mongodb"

  - name: MongoDB.Driver
    language: C#
    type: Driver
    repo: "mongodb/mongo-csharp-driver"
    nuget: "MongoDB.Driver"
    stackoverflow: "mongodb"

  - name: Mongoid
    language: Ruby
    type: ODM
    repo: "mongodb/mongoid"
    rubygems: "mongoid"
    stackoverflow: "mongoid"

  - name: Motor
    language: Python
    type: Async ODM
    repo: "mongodb/motor"
    pypi: "motor"
    stackoverflow: "motor"

  - name: mongodb Rust driver
    language: Rust
    type: Driver
    repo: "mongodb/mongo-rust-driver"
    crates: "mongodb"
    stackoverflow: "mongodb"

  # Additional repos synced from alexbevi/scrape_dependents/repos.json
  - name: mongo-ruby-driver
    language: Ruby
    type: Driver
    repo: "mongodb/mongo-ruby-driver"

  - name: node-mongodb-native
    language: JavaScript
    type: Driver
    repo: "mongodb/node-mongodb-native"

  - name: mongo-java-driver
    language: Java
    type: Driver
    repo: "mongodb/mongo-java-driver"

  - name: mongo-python-driver
    language: Python
    type: Driver
    repo: "mongodb/mongo-python-driver"

  - name: mongo-go-driver
    language: Go
    type: Driver
    repo: "mongodb/mongo-go-driver"

  - name: drizzle-orm
    language: JavaScript
    type: ORM
    repo: "drizzle-team/drizzle-orm"

  - name: mongoengine
    language: Python
    type: ODM
    repo: "MongoEngine/mongoengine"

  - name: typeorm
    language: JavaScript
    type: ORM
    repo: "typeorm/typeorm"

  - name: langchaingo
    language: Go
    type: AI
    repo: "tmc/langchaingo"

  - name: langchainjs
    language: JavaScript
    type: AI
    repo: "langchain-ai/langchainjs"

  - name: langchain-mongodb
    language: Python
    type: AI
    repo: "langchain-ai/langchain-mongodb"

  - name: llama_index
    language: Python
    type: AI
    repo: "run-llama/llama_index"

  - name: mongomapper
    language: Ruby
    type: ODM
    repo: "mongomapper/mongomapper"

  - name: beanie
    language: Python
    type: ODM
    repo: "BeanieODM/beanie"

  - name: doctrine-mongodb-odm
    language: PHP
    type: ODM
    repo: "doctrine/mongodb-odm"

  - name: txmongo
    language: Python
    type: Driver
    repo: "twisted/txmongo"

  - name: djongo
    language: Python
    type: Framework
    repo: "doableware/djongo"

  - name: mongo_dart
    language: Dart
    type: Driver
    repo: "mongo-dart/mongo_dart"

  - name: morphia
    language: Java
    type: Framework
    repo: "MorphiaOrg/morphia"

  - name: langchain4j
    language: Java
    type: AI
    repo: "langchain4j/langchain4j"

  - name: mongo-php-library
    language: PHP
    type: Driver
    repo: "mongodb/mongo-php-library"

  - name: laravel-mongodb
    language: PHP
    type: Framework
    repo: "mongodb/laravel-mongodb"

  - name: mongo-efcore-provider
    language: CSharp
    type: Framework
    repo: "mongodb/mongo-efcore-provider"

  - name: DoctrineMongoDBBundle
    language: PHP
    type: Framework
    repo: "doctrine/DoctrineMongoDBBundle"

  - name: django-mongodb-backend
    language: Python
    type: Framework
    repo: "mongodb/django-mongodb-backend"