projects:
  - name: mongoose
    language: JavaScript
    type: ODM
    repo: "Automattic/mongoose"
    npm: "mongoose"
    stackoverflow: "mongoose"

  - name: Prisma MongoDB
    language: JavaScript
    type: ORM
    repo: "prisma/prisma"
    npm: "prisma"
    stackoverflow: "prisma"

  - name: Spring Data MongoDB
    language: Java
    type: Framework
    repo: "spring-projects/spring-data-mongodb"
    package_id: "UGFja2FnZS0xODAwNzIyMDI%3D"
    maven:
      group: "org.springframework.data"
      artifact: "spring-data-mongodb"
    stackoverflow: "spring-data-mongodb"

  - name: MongoDB.Driver
    language: C#
    type: Driver
    repo: "mongodb/mongo-csharp-driver"
    nuget: "MongoDB.Driver"
    package_id: "UGFja2FnZS0xNTY4MDUzMzI%3D"
    stackoverflow: "mongodb-.net-driver"

  - name: Mongoid
    language: Ruby
    type: ODM
    repo: "mongodb/mongoid"
    rubygems: "mongoid"
    stackoverflow: "mongoid"

  - name: Motor
    language: Python
    type: ODM
    repo: "mongodb/motor"
    pypi: "motor"
    stackoverflow: "motor"

  - name: MongoDB Rust driver
    language: Rust
    type: Driver
    repo: "mongodb/mongo-rust-driver"
    crates: "mongodb"
    package_id: "UGFja2FnZS0zMjE2OTgyMTk5"
    stackoverflow: "mongodb"

  # Additional repos synced from alexbevi/scrape_dependents/repos.json
  - name: mongo-ruby-driver
    language: Ruby
    type: Driver
    repo: "mongodb/mongo-ruby-driver"
    rubygems: "mongo"
    package_id: "UGFja2FnZS0xMDQwOQ%3D%3D"
    stackoverflow: "mongodb"

  - name: node-mongodb-native
    language: JavaScript
    type: Driver
    repo: "mongodb/node-mongodb-native"
    npm: "mongodb"
    stackoverflow: "mongodb"

  - name: mongo-java-driver
    language: Java
    type: Driver
    repo: "mongodb/mongo-java-driver"
    maven:
      group: "org.mongodb"
      artifact: "mongodb-driver-sync"
    stackoverflow: "mongodb java"

  - name: mongo-python-driver
    language: Python
    type: Driver
    repo: "mongodb/mongo-python-driver"
    pypi: "pymongo"
    package_id: "UGFja2FnZS01MjQ3ODA0NA%3D%3D"
    stackoverflow: "mongodb python"

  - name: mongo-go-driver
    language: Go
    type: Driver
    repo: "mongodb/mongo-go-driver"
    go: "go.mongodb.org/mongo-driver"
    stackoverflow: "mongodb go"

  - name: drizzle-orm
    language: JavaScript
    type: ORM
    repo: "drizzle-team/drizzle-orm"
    npm: "drizzle-orm"
    stackoverflow: "drizzle-orm"

  - name: mongoengine
    language: Python
    type: ODM
    repo: "MongoEngine/mongoengine"
    pypi: "mongoengine"
    stackoverflow: "mongoengine"

  - name: typeorm
    language: JavaScript
    type: ORM
    repo: "typeorm/typeorm"
    npm: "typeorm"
    stackoverflow: "typeorm"

  - name: langchaingo
    language: Go
    type: AI
    repo: "tmc/langchaingo"
    go: "github.com/tmc/langchaingo"
    stackoverflow: "langchaingo"

  - name: langchainjs
    language: JavaScript
    type: AI
    repo: "langchain-ai/langchainjs"
    npm: "langchain"
    stackoverflow: "langchain"

  - name: langchain-mongodb
    language: Python
    type: AI
    repo: "langchain-ai/langchain-mongodb"
    pypi: "langchain"
    stackoverflow: "langchain"

  - name: llama_index
    language: Python
    type: AI
    repo: "run-llama/llama_index"
    pypi: "llama-index"
    stackoverflow: "llama-index"

  - name: mongomapper
    language: Ruby
    type: ODM
    repo: "mongomapper/mongomapper"
    rubygems: "mongomapper"
    package_id: "UGFja2FnZS0xNzU0"
    stackoverflow: "mongomapper"

  - name: beanie
    language: Python
    type: ODM
    repo: "BeanieODM/beanie"
    pypi: "beanie"
    stackoverflow: "beanie"

  - name: doctrine-mongodb-odm
    language: PHP
    type: ODM
    repo: "doctrine/mongodb-odm"
    packagist: "doctrine/mongodb-odm"
    stackoverflow: "doctrine-mongodb-odm"

  - name: txmongo
    language: Python
    type: Driver
    repo: "twisted/txmongo"
    pypi: "txmongo"
    stackoverflow: "txmongo"

  - name: djongo
    language: Python
    type: Framework
    repo: "doableware/djongo"
    pypi: "djongo"
    stackoverflow: "djongo"

  - name: mongo_dart
    language: Dart
    type: Driver
    repo: "mongo-dart/mongo_dart"
    stackoverflow: "mongo-dart"

  - name: morphia
    language: Java
    type: Framework
    repo: "MorphiaOrg/morphia"
    maven:
      group: "dev.morphia.morphia"
      artifact: "morphia-core"
    stackoverflow: "morphia"

  - name: langchain4j
    language: Java
    type: AI
    repo: "langchain4j/langchain4j"
    maven:
      group: "dev.langchain4j"
      artifact: "langchain4j"
    stackoverflow: "langchain4j"

  - name: mongo-php-library
    language: PHP
    type: Driver
    repo: "mongodb/mongo-php-library"
    packagist: "mongodb/mongodb"
    package_id: "UGFja2FnZS01NDM1MTQ3ODc%3D"
    stackoverflow: "mongodb"

  - name: laravel-mongodb
    language: PHP
    type: Framework
    repo: "mongodb/laravel-mongodb"
    packagist: "mongodb/laravel-mongodb"
    stackoverflow: "mongodb"

  - name: mongo-efcore-provider
    language: C#
    type: Framework
    repo: "mongodb/mongo-efcore-provider"
    nuget: "MongoDB.EntityFrameworkCore"
    package_id: "UGFja2FnZS00MDk5MTY0NzQy"
    stackoverflow: "mongodb"

  - name: DoctrineMongoDBBundle
    language: PHP
    type: Framework
    repo: "doctrine/DoctrineMongoDBBundle"
    packagist: "doctrine/doctrine-mongodb-bundle"
    stackoverflow: "doctrine-mongodb-bundle"

  - name: django-mongodb-backend
    language: Python
    type: Framework
    repo: "mongodb/django-mongodb-backend"
    pypi: "django-mongodb-backend"
    stackoverflow: "django-mongodb-backend"

  # --- appended projects (only new ones from user's list) ---
  - name: .NET Aspire
    language: C#
    type: Framework
    repo: "dotnet/aspire"
    stackoverflow: "dotnet-aspire"

  - name: Actix
    language: Rust
    type: Framework
    repo: "actix/actix-web"
    crates: "actix"
    stackoverflow: "actix"

  - name: Aeria
    language: JavaScript
    type: Framework
    repo: "aeria-org/aeria"
    stackoverflow: "aeria"

  - name: Agno
    language: Python
    type: AI
    repo: "agno-agi/agno"
    pypi: "agno"
    stackoverflow: "agno"

  - name: Apache Beam
    language: Multi
    type: Framework
    repo: "apache/beam"
    stackoverflow: "apache-beam"

  - name: Axum
    language: Rust
    type: Framework
    repo: "tokio-rs/axum"
    crates: "axum"
    stackoverflow: "rust-axum"

  - name: cryomongo
    language: Crystal
    type: Library
    repo: "elbywan/cryomongo"
    stackoverflow: "cryomongo"

  - name: Dart Driver
    language: Dart
    type: Library
    repo: "mongo-dart/mongo_dart"
    stackoverflow: "dart"

  - name: Diesel
    language: Rust
    type: ORM
    crates: "diesel"
    repo: "diesel-rs/diesel"
    stackoverflow: "diesel"

  - name: Elixir Driver
    language: Elixir
    type: Library
    repo: "zookzook/elixir-mongodb-driver"
    stackoverflow: "elixir"

  - name: Elsa
    language: C#
    type: Library
    repo: "elsa-workflows/elsa-core"
    nuget: "Elsa"
    stackoverflow: "elsa-workflows"

  - name: Entity Framework Core
    language: C#
    type: Framework
    repo: "dotnet/efcore"
    nuget: "Microsoft.EntityFrameworkCore"
    stackoverflow: "entity-framework-core"

  - name: FastAPI
    language: Python
    type: Framework
    repo: "fastapi/fastapi"
    pypi: "fastapi"
    stackoverflow: "fastapi"

  - name: Flask
    language: Python
    type: Framework
    repo: "pallets/flask"
    pypi: "Flask"
    stackoverflow: "flask"

  - name: Flask PyMongo
    language: Python
    type: Framework
    pypi: "Flask-PyMongo"
    repo: "mongodb-labs/flask-pymongo"
    stackoverflow: "flask-pymongo"

  - name: Flowise
    language: JavaScript
    type: AI
    repo: "flowiseai/flowise"
    npm: "flowise"
    stackoverflow: "flowise"

  - name: FormIO
    language: JavaScript
    type: Other
    repo: "formio/formio"
    npm: "formio"
    stackoverflow: "formio"

  - name: GORM
    language: Go
    type: Framework
    repo: "go-gorm/gorm"
    stackoverflow: "gorm"

  - name: GORM for MongoDB
    language: Java
    type: Framework
    repo: "jkuehn/gorm-mongodb"
    stackoverflow: "gorm mongodb"

  - name: Gotham
    language: Rust
    type: Framework
    repo: "gotham-rs/gotham"
    crates: "gotham"
    stackoverflow: "gotham"

  - name: Hangfire
    language: C#
    type: Library
    repo: "HangfireIO/Hangfire"
    nuget: "Hangfire"
    stackoverflow: "hangfire"

  - name: Hangfire.Mongo
    language: C#
    type: Library
    nuget: "Hangfire.Mongo"
    repo: "gottscj/Hangfire.Mongo"
    stackoverflow: "hangfire"

  - name: Haskell Driver
    language: Haskell
    type: Driver
    repo: "mongodb-haskell/mongodb"
    stackoverflow: "haskell"

  - name: Hasura
    language: Rust
    type: Other
    repo: "hasura/graphql-engine"
    stackoverflow: "hasura"

  - name: Haystack
    language: Python
    type: AI
    repo: "deepset-ai/haystack"
    pypi: "farm-haystack"
    stackoverflow: "haystack"

  - name: MongoDB Extension for Hibernate
    language: Java
    type: Framework
    repo: "mongodb/mongo-hibernate"
    stackoverflow: "hibernate"

  - name: Hibernate OGM
    language: Java
    type: Framework
    repo: "hibernate/hibernate-ogm"
    stackoverflow: "hibernate-ogm"

  - name: KeystoneJS
    language: JavaScript
    type: Framework
    repo: "keystonejs/keystone"
    npm: "keystone"
    stackoverflow: "keystonejs"

  - name: Langgraph
    language: Multi
    type: AI
    repo: "langchain-ai/langgraph"
    stackoverflow: "langgraph"

  - name: Laravel
    language: PHP
    type: Framework
    repo: "laravel/laravel"
    packagist: "laravel/laravel"
    stackoverflow: "laravel"

  - name: Loco
    language: Rust
    type: Framework
    crates: "loco"
    repo: "loco-rs/loco"
    stackoverflow: "loco"

  - name: MassTransit
    language: C#
    type: Framework
    repo: "MassTransit/MassTransit"
    nuget: "MassTransit"
    stackoverflow: "masstransit"

  - name: Meteor
    language: JavaScript
    type: Framework
    repo: "meteor/meteor"
    npm: "meteor"
    stackoverflow: "meteor"

  - name: mgo
    language: Go
    type: Driver
    repo: "globalsign/mgo"
    stackoverflow: "mgo"

  - name: Microsoft Semantic Kernel
    language: Multi
    type: AI
    repo: "microsoft/semantic-kernel"
    stackoverflow: "semantic-kernel"

  - name: MikroORM
    language: JavaScript
    type: ORM
    repo: "mikro-orm/mikro-orm"
    npm: "mikro-orm"
    stackoverflow: "mikroorm"

  - name: Monarch
    language: JavaScript
    type: ORM
    repo: "monarch-orm/monarch"
    npm: "monarch-orm"
    stackoverflow: "monarch"

  - name: mongolite
    language: R
    type: Driver
    repo: "jeroen/mongolite"
    stackoverflow: "mongolite"

  - name: mongoon
    language: Crystal
    type: ODM
    repo: "elbywan/moongoon"
    stackoverflow: "mongoon"

  - name: mORMot2
    language: Pascal
    type: Library
    repos: "synopse/mORMot2"
    stackoverflow: "mormot2"

  - name: OData
    language: C#
    type: Library
    repo: "OData/AspNetCoreOData"
    nuget: "Microsoft.OData.Core"
    stackoverflow: "odata"

  - name: ODMantic
    language: Python
    type: ODM
    repo: "art049/odmantic"
    pypi: "odmantic"
    stackoverflow: "odmantic"

  - name: Papr
    language: JavaScript
    type: Library
    repo: "plexinc/papr"
    npm: "papr"
    stackoverflow: "papr"

  - name: Pavex
    language: Rust
    type: Framework
    repo: "LukeMathWalker/pavex"
    crates: "pavex"
    stackoverflow: "pavex"

  - name: Perl Driver
    language: Perl
    type: Driver
    repo: "mongodb-labs/mongo-perl-driver"
    stackoverflow: "perl"

  - name: Poem
    language: Rust
    type: Framework
    crates: "poem"
    repo: "poem-web/poem"
    stackoverflow: "poem"

  - name: PyMODM
    language: Python
    type: ODM
    repo: "mongodb/pymodm"
    pypi: "pymodm"
    stackoverflow: "pymodm"

  - name: Quarkus
    language: Java
    type: Framework
    repo: "quarkusio/quarkus"
    stackoverflow: "quarkus"

  - name: Redwood
    language: JavaScript
    type: Framework
    repo: "redwoodjs/graphql"
    npm: "@redwoodjs/cli"
    stackoverflow: "redwoodjs"

  - name: RESTHeart
    language: Java
    type: Framework
    repo: "softinstigate/restheart"
    stackoverflow: "restheart"

  - name: Rocket
    language: Rust
    type: Framework
    repo: "SergioBenitez/rocket"
    crates: "rocket"
    stackoverflow: "rocket"

  - name: RxDB
    language: JavaScript
    type: Other
    repo: "pubkey/rxdb"
    npm: "rxdb"
    stackoverflow: "rxdb"

  - name: Sails
    language: JavaScript
    type: Framework
    repo: "balderdashy/sails"
    stackoverflow: "sailsjs"
    npm: "sails"

  - name: Sails MongoDB
    language: JavaScript
    type: Library
    repo: "balderdashy/sails-mongo"
    npm: "sails-mongo"
    stackoverflow: "sailsjs"

  - name: Salvo
    language: Rust
    type: Framework
    crates: "salvo"
    repo: "salvo-rs/salvo"
    stackoverflow: "salvo"

  - name: Sea-ORM
    language: Rust
    crates: "sea-orm"
    type: ORM
    repo: "SeaQL/sea-orm"
    stackoverflow: "sea-orm"

  - name: Spring Boot
    language: Java
    type: Framework
    repo: "spring-projects/spring-boot"
    stackoverflow: "spring-boot"

  - name: Symfony
    language: PHP
    type: Framework
    repo: "symfony/symfony"
    packagist: "symfony/symfony"
    stackoverflow: "symfony"

  - name: Thruster
    language: Rust
    type: Framework
    crates: "thruster"
    repo: "thruster-rs/thruster"
    stackoverflow: "thruster"

  - name: Tide
    language: Rust
    type: Framework
    repo: "http-rs/tide"
    crates: "tide"
    stackoverflow: "tide"

  - name: Toasty
    language: Rust
    type: ORM
    crates: "toasty"
    repo: "tokio-rs/toasty"
    stackoverflow: "toasty"

  - name: unstorage
    language: JavaScript
    type: Library
    repo: "unjs/unstorage"
    npm: "unstorage"
    stackoverflow: "unstorage"

  - name: Warp
    language: Rust
    crates: "warp"
    type: Framework
    repo: "seanmonstar/warp"
    stackoverflow: "warp"

  - name: Waterline
    language: JavaScript
    type: ORM
    repo: "balderdashy/waterline"
    npm: "waterline"
    stackoverflow: "waterline"

  - name: Zig Driver
    language: Zig
    type: Driver
    repo: "softprops/zig-mongodb"
    stackoverflow: "zig"

  - name: Parse Server SDK
    language: JavaScript
    type: Framework
    repo: "parse-community/Parse-SDK-JS"
    stackoverflow: "parse-server"
    npm: "parse"

  - name: PowerSync
    language: JavaScript
    type: Framework
    repo: "powersync-ja/powersync-service"
    npm: "powersync"
    stackoverflow: "powersync"

  - name: Mongeese
    language: JavaScript
    type: Other
    repo: "michael-nwuju/mongeese"
    npm: "mongeese-cli"
    stackoverflow: "mongeese"

  - name: n8n
    language: JavaScript
    type: AI
    npm: "n8n"
    repo: "n8n-io/n8n"
    stackoverflow: "n8n"

  - name: Litestar
    language: Python
    type: Framework
    pypi: "litestar"
    repo: "litestar-org/litestar"
    stackoverflow: "litestar"

  - name: Quartz MongoDB
    language: Java
    type: Library
    repo: "avi-sanwal/quartz-mongodb"
    maven:
      group: "com.novemberain"
      artifact: "quartz-mongodb"
    stackoverflow: "quartz-scheduler"

  - name: Quartz Scheduler
    language: Java
    type: Library
    maven:
      group: "org.quartz-scheduler"
      artifact: "quartz"
    repo: "quartz-scheduler/quartz"
    stackoverflow: "quartz-scheduler"

  - name: KMongo
    language: Kotlin
    type: Driver
    repo: "Litote/kmongo"
    maven:
      group: "org.litote.kmongo"
      artifact: "kmongo"
    stackoverflow: "kmongo"


  - name: PowerShell Cmdlets
    language: C#
    type: Library
    repo: "nightroman/Mdbc"
    stackoverflow: "powershell mongodb"

  - name: MongoKitten
    language: Swift
    type: Driver
    repo: "OpenKitten/MongoKitten"
    stackoverflow: "mongokitten"
    package_id: "UGFja2FnZS0yMDk4MjcxMTI%3D"
