name: Popularity Index

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"  # 03:17 UTC daily

jobs:
  matrix-prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Generate matrix from projects.yml
        id: set-matrix
        run: |
          node scripts/matrix-from-projects.cjs > matrix.json
          echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
          cat matrix.json >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Show generated matrix
        run: |
          echo "--- matrix.json ---"
          cat matrix.json || true
          echo "--- end matrix ---"

  scrape:
    needs: matrix-prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix-prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Scrape single project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_VERBOSE: 1
          OWNER: ${{ matrix.owner }}
          REPO: ${{ matrix.repo }}
        run: |
          # run build for a single repo and write per-repo JSON (wrapper script)
          # If the scraper fails, write an empty array file so aggregation can continue and do not fail the job
          node scripts/scrape-single.cjs "${{ matrix.owner }}" "${{ matrix.repo }}" "${{ matrix.repo_full }}" || (
            echo "[]" > "data/popularity.${{ matrix.owner }}.${{ matrix.repo }}.json" ;
            echo "Scrape failed for ${{ matrix.repo_full }}, wrote empty artifact and continuing";
          )
      - name: Upload per-repo artifact
        uses: actions/upload-artifact@v4
        with:
          name: per-repo-popularity-${{ matrix.owner }}-${{ matrix.repo }}
          path: |
            data/popularity.${{ matrix.owner }}.${{ matrix.repo }}.json

  aggregate:
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Download per-repo artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./
      - name: Aggregate artifacts into data/popularity.json
        run: |
          node scripts/aggregate-artifacts.cjs
      - name: Generate output README
        run: node scripts/generate-readme.js
      - name: Push data to output branch
        env:
          OUTPUT_BRANCH: output
          GIT_EMAIL: actions@github.com
          GIT_NAME: github-actions
        run: |
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_NAME"
          git checkout --orphan $OUTPUT_BRANCH
          git rm -rf --cached . || true
          TMP_DIR=$(mktemp -d)
          cp -R data "$TMP_DIR" || true
          cp -R web "$TMP_DIR" || true
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} + || true
          if [ -d "$TMP_DIR/web" ]; then
            cp -R "$TMP_DIR/web/." . || true
          fi
          if [ -d "$TMP_DIR/data" ]; then
            mkdir -p data
            cp -R "$TMP_DIR/data/." ./data || true
          fi
          if [ -f ./data/popularity.json ]; then cp ./data/popularity.json ./popularity.json || true; fi
          rm -rf "$TMP_DIR"
          git add --all
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(popularity): refresh data"
            git push --force origin $OUTPUT_BRANCH
          fi