name: Redeploy web UI and data

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message for the output branch'
        required: false
        default: 'Redeploy web UI and popularity data'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Check for generated data
        id: check_data
        run: |
          if [ -f data/popularity.json ]; then
            echo "data_present=true" >> $GITHUB_OUTPUT
          else
            echo "data_present=false" >> $GITHUB_OUTPUT
          fi

      - name: Prepare output branch worktree
        env:
          OUTPUT_BRANCH: output
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Create a worktree for the output branch (create branch if missing)
          WT_DIR="/tmp/output"
          rm -rf "$WT_DIR"
          if git show-ref --verify --quiet refs/heads/${OUTPUT_BRANCH}; then
            git worktree add "$WT_DIR" ${OUTPUT_BRANCH}
          else
            git worktree add -b ${OUTPUT_BRANCH} "$WT_DIR"
          fi

          # Clean and copy files we want to publish (web UI + generated data)
          rm -rf "$WT_DIR"/*
          mkdir -p "$WT_DIR"
          # Copy web directory contents
          rsync -a --delete --exclude='.git' web/ "$WT_DIR/"
          # Ensure the generated data is included at the repo root on the output branch (if present)
          if [ -f data/popularity.json ]; then
            cp data/popularity.json "$WT_DIR/popularity.json"
            echo "including data in deploy"
          else
            echo "no generated data found; deploying UI only"
          fi

          # Commit and push
          cd "$WT_DIR"
          git add -A
          # If data was present, use the provided message; otherwise annotate.
          if [ -f "$WT_DIR/popularity.json" ]; then
            git commit -m "${{ github.event.inputs.message }}" || echo "No changes to commit"
          else
            git commit -m "${{ github.event.inputs.message }} (UI only, no data present)" || echo "No changes to commit"
          fi
          git push origin ${OUTPUT_BRANCH} --force

      - name: Finish
        run: echo "Redeploy complete"
